name: 'docs-build'
description: 'All the steps required to build the docs'
runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v5
      with:
          python-version: "3.9"
          cache: "pip"
          cache-dependency-path: "pyproject.toml"

    - shell: bash
      run: pip install "tox==4.4.3"
    - shell: bash
      env:
        C_INCLUDE_PATH: ${{ env.pythonLocation }}/include/python3.9
      run: tox run -e docs-build

