name: 'docs-build'
description: 'All the steps required to build the docs'
inputs:
  cache-dependency-path:
    description: "Cache path to pass to setup-python"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v5
      if: ${{ inputs.cache-dependency-path != "" }}
      with:
        python-version: "3.9"
        cache: "pip"
        cache-dependency-path: ${{ inputs.cache-dependency-path }}

    - uses: actions/setup-python@v5
      if: ${{ inputs.cache-dependency-path == "" }}
      with:
        python-version: "3.9"
        cache: "pip"

    - shell: bash
      run: pip install "tox==4.4.3"
    - shell: bash
      env:
        C_INCLUDE_PATH: ${{ env.pythonLocation }}/include/python3.9
      run: tox run -e docs-build

