name: Dissect CI Template
on:
  workflow_call:
    inputs:
      run_tests:
        required: false
        type: boolean
        default: true
      run_linting:
        required: false
        type: boolean
        default: true
      on-demand-test:
        required: false
        type: string
        default: ""
      deb-packages:
        required: false
        type: string
        default: ""

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - if: ${{ inputs.deb-packages != '' }}
        run: sudo apt-get install -qq ${{ inputs.deb-packages }}
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      - run: git lfs pull
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          cache: "pip"
          cache-dependency-path: "pyproject.toml"
      - run: pip install "tox==4.2.4"
      - if: ${{ github.ref_name == 'main' }}
        run: sed -i 's/\[tool.setuptools_scm\]/\[tool.setuptools_scm\]\nlocal_scheme = "no-local-version"/' pyproject.toml
      - env:
          C_INCLUDE_PATH: ${{ env.pythonLocation }}/include/python3.9
        run: tox run -e build
      - uses: actions/upload-artifact@v3
        with:
          name: packages
          path: dist/*
          retention-days: 1

  lint:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - if: ${{ inputs.run_linting == true }}
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      - if: ${{ inputs.run_linting == true }}
        run: git lfs pull
      - if: ${{ inputs.run_linting == true }}
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          cache: "pip"
          cache-dependency-path: "pyproject.toml"
      - if: ${{ inputs.run_linting == true }}
        run: pip install "tox==4.2.4"
      - if: ${{ inputs.run_linting == true && github.ref_name == 'main' }}
        run: sed -i 's/\[tool.setuptools_scm\]/\[tool.setuptools_scm\]\nlocal_scheme = "no-local-version"/' pyproject.toml
      - if: ${{ inputs.run_linting == true }}
        env:
          C_INCLUDE_PATH: ${{ env.pythonLocation }}/include/python3.9
        run: tox run -e lint

  test:
    needs: build
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.allow_failure }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - python-version: "3.9"
            python-include: "python3.9"
            tox-env: "py39"
            allow_failure: false
          - python-version: "3.10"
            python-include: "python3.10"
            tox-env: "py310"
            allow_failure: false
          - python-version: "3.11"
            python-include: "python3.11"
            tox-env: "py311"
            allow_failure: true 
          - python-version: "pypy3.9"
            python-include: "pypy3.9"
            tox-env: "pypy39"
            allow_failure: false
    steps:
      - if: ${{ inputs.run_tests == true && inputs.deb-packages != '' }}
        run: sudo apt-get install -qq ${{ inputs.deb-packages }}
      - if: ${{ inputs.run_tests == true }}
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      - if: ${{ inputs.run_tests == true }}
        run: git lfs pull
      - if: ${{ inputs.run_tests == true }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
          cache-dependency-path: "pyproject.toml"
      - if: ${{ inputs.run_tests == true }}
        run: pip install "tox==4.2.4"
      - if: ${{ inputs.run_tests == true && github.ref_name == 'main' }}
        run: sed -i 's/\[tool.setuptools_scm\]/\[tool.setuptools_scm\]\nlocal_scheme = "no-local-version"/' pyproject.toml
      - if: ${{ inputs.run_tests == true }}
        env:
          C_INCLUDE_PATH: ${{ env.pythonLocation }}/include/${{ matrix.python-include }}
        run: tox run -e ${{ matrix.tox-env }}
      - if: ${{ inputs.run_tests == true }}
        uses: codecov/codecov-action@v3
        with:
          env_vars: PYTHON
          files: coverage.xml
          flags: unittests
          verbose: true
      - if: ${{ inputs.run_tests == true }}
        uses: actions/upload-artifact@v3
        with:
          name: coverage
          path: coverage.xml

  on-demand-test:
    if: ${{ inputs.on-demand-test != '' }}
    runs-on: ubuntu-latest
    steps:
      - env:
          REPO_NAME: ${{ inputs.on-demand-test }}
        run: |
          curl \
               --no-progress-meter \
               -X POST \
               -H "Accept: application/vnd.github+json" \
               -H "Authorization: Bearer ${{ secrets.DISSECT_PA_TOKEN }}" \
               "https://api.github.com/repos/fox-it/${REPO_NAME}/dispatches" \
               -d '{"event_type":"on-demand-test"}'
