name: Dissect CI Template
on:
  workflow_call:
    inputs:
      run-tests:
        required: false
        type: boolean
        default: true
      run-linting:
        required: false
        type: boolean
        default: true
      run-docs:
        required: false
        type: boolean
        default: true
      run-benchmarks:
        required: false
        type: boolean
        default: false
      deb-packages:
        required: false
        type: string
        default: ""

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - if: ${{ inputs.deb-packages != '' }}
        run: sudo apt-get install -qq ${{ inputs.deb-packages }}

      - uses: fox-it/dissect-workflow-templates/.github/actions/git-checkout@main

      - uses: fox-it/dissect-workflow-templates/.github/actions/tox-run@main
        with:
          tox-environment: build

      - uses: actions/upload-artifact@v4
        with:
          name: packages
          path: dist/*
          retention-days: 1

  lint:
    needs: build
    runs-on: ubuntu-latest
    if: ${{ inputs.run-linting == true }}
    steps:
      - uses: fox-it/dissect-workflow-templates/.github/actions/git-checkout@main

      - uses: fox-it/dissect-workflow-templates/.github/actions/tox-run@main
        with:
          tox-environment: lint

  docs-build:
    needs: build
    runs-on: ubuntu-latest
    if: ${{ inputs.run-docs == true}}
    continue-on-error: true
    steps:
      - uses: fox-it/dissect-workflow-templates/.github/actions/git-checkout@main

      - uses: fox-it/dissect-workflow-templates/.github/actions/tox-run@main
        with:
          tox-environment: docs-build

  test:
    needs: build
    runs-on: ${{ matrix.os }}
    if: ${{ inputs.run-tests == true }}
    continue-on-error: ${{ matrix.allow_failure }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "windows-latest"]
        python-version: ["3.9", "pypy3.9", "pypy3.10", "pypy3.11", "3.10", "3.11", "3.12", "3.13"]
        include:
          - allow_failure: false
            tox-version: "4.4.3"
            include-prefix: "python"
          - python-version: "pypy3.9"
            include-prefix: ""
          - python-version: "pypy3.9"
            os: "windows-latest"
            include-prefix: ""
            allow_failure: true
          - python-version: "pypy3.10"
            include-prefix: ""
            allow_failure: true
          - python-version: "pypy3.11"
            include-prefix: ""
            allow_failure: true
          - python-version: "3.12"
            allow_failure: true
          - python-version: "3.13"
            allow_failure: true
    steps:
      - if: ${{ inputs.deb-packages != '' && ! startsWith(matrix.os, 'windows') }}
        run: sudo apt-get install -qq ${{ inputs.deb-packages }}

      - uses: fox-it/dissect-workflow-templates/.github/actions/git-checkout@main

      - uses: fox-it/dissect-workflow-templates/.github/actions/tox-run@main
        with:
          tox-environment: ${{ matrix.python-version }}
          runner-os: ${{ matrix.os }}
          python-version: ${{ matrix.python-version }}
          include-prefix: ${{ matrix.include-prefix }}

      - uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.DISSECT_CODECOV_TOKEN }}
          env_vars: PYTHON
          files: coverage.xml
          flags: unittests
          verbose: true

  benchmark:
    needs: build
    runs-on: ubuntu-latest
    if: ${{ inputs.run-benchmarks == true}}
    continue-on-error: true
    steps:
      - uses: fox-it/dissect-workflow-templates/.github/actions/git-checkout@main

      - uses: fox-it/dissect-workflow-templates/.github/actions/tox-run@main
        with:
          tox-environment: benchmark
          python-version: "3.13"
