name: Dissect Self Hosted CI Template
on:
  workflow_call:
    inputs:
      run_tests:
        required: false
        type: boolean
        default: true
      run_docs:
        required: false
        type: boolean
        default: true
      run_linting:
        required: false
        type: boolean
        default: true

jobs:
  build:
    runs-on: ubuntu-latest-sh
    steps:
      #TODO: Before merge, change to @main
      - uses: fox-it/dissect-workflow-templates/.github/actions/git-checkout@cleanup
      - uses: fox-it/dissect-workflow-templates/.github/actions/tox-run@cleanup
        with:
          tox-environment: build

      - uses: actions/upload-artifact@v4
        with:
          name: packages
          path: dist/*
          retention-days: 1

  lint:
    needs: build
    runs-on: ubuntu-latest-sh
    if: ${{ inputs.run_linting == true }}

    steps:
      #TODO: Before merge, change to @main
      - uses: fox-it/dissect-workflow-templates/.github/actions/git-checkout@cleanup

      - uses: fox-it/dissect-workflow-templates/.github/actions/tox-run@cleanup
        with:
          tox-environment: lint

      - env:
          C_INCLUDE_PATH: ${{ env.pythonLocation }}/include/python3.9
        run: tox run -e lint

  docs-build:
    needs: build
    runs-on: ubuntu-latest-sh
    if: ${{ inputs.run_docs == true}}
    steps:
      - uses: fox-it/dissect-workflow-templates/.github/actions/git-checkout@cleanup

      - uses: fox-it/dissect-workflow-templates/.github/actions/tox-run@cleanup
        with:
          tox-environment: docs-build


  test:
    needs: build
    runs-on: ${{ matrix.os }}
    if: ${{ inputs.run_tests == true }}
    continue-on-error: ${{ matrix.allow_failure }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest-sh"]
        python-version: ["3.9", "pypy3.9", "pypy3.10", "3.10", "3.11", "3.12", "3.13"]
        include:
          - allow_failure: false
            tox-version: "4.2.4"
            include-prefix: "python"
          - python-version: "pypy3.9"
            include-prefix: ""
          - python-version: "pypy3.10"
            include-prefix: ""
            allow_failure: true
          - python-version: "3.12"
            allow_failure: true
          - python-version: "3.13"
            allow_failure: true
    steps:
      - if: ${{ inputs.run_tests == true && inputs.deb-packages != '' && ! startsWith(matrix.os, 'windows') }}
        run: sudo apt-get install -qq ${{ inputs.deb-packages }}

      #TODO: Before merge, change to @main
      - uses: fox-it/dissect-workflow-templates/.github/actions/git-checkout@cleanup
      - uses: fox-it/dissect-workflow-templates/.github/actions/tox-run@cleanup
        with:
          tox-environment: "${{ matrix.python-version }}"
          runner-os: "${{ matrix.os }}"
          python-version: "${{ matrix.python-version }}"
          include-prefix: "${{ matrix.include-prefix }}"


      - uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.DISSECT_CODECOV_TOKEN }}
          env_vars: PYTHON
          files: coverage.xml
          flags: unittests
          verbose: true

  publish:
    needs: [lint, test]
    if: ${{ github.ref_name == 'main' || github.ref_type == 'tag' }}
    runs-on: ubuntu-latest-sh
    environment: dissect_publish
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: packages
          path: dist/
      - name: Publish package to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: ${{ secrets.DISSECT_PRIVATE_PYPI_USERNAME }}
          password: ${{ secrets.DISSECT_PRIVATE_PYPI_PASSWORD }}
          repository-url: ${{ secrets.DISSECT_PRIVATE_PYPI_REPOSITORY }}
