name: Dissect Self Hosted CI Template
on:
  workflow_call:
    inputs:
      run_tests:
        required: false
        type: boolean
        default: true
      run_linting:
        required: false
        type: boolean
        default: true

jobs:
  build:
    runs-on: ubuntu-latest-sh
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      - run: git lfs pull
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          cache: "pip"
          cache-dependency-path: "pyproject.toml"
      - run: pip install "tox==4.2.4"
      - if: ${{ github.ref_name == 'main' }}
        run: sed -i 's/\[tool.setuptools_scm\]/\[tool.setuptools_scm\]\nlocal_scheme = "no-local-version"/' pyproject.toml
      - env:
          PIP_INDEX_URL: ${{ secrets.DISSECT_PIP_INDEX_URL }}
          C_INCLUDE_PATH: ${{ env.pythonLocation }}/include/python3.9
        run: tox run -e build
      - uses: actions/upload-artifact@v3
        with:
          name: packages
          path: dist/*
          retention-days: 1

  lint:
    needs: build
    runs-on: ubuntu-latest-sh
    steps:
      - if: ${{ inputs.run_linting == true }}
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      - if: ${{ inputs.run_linting == true }}
        run: git lfs pull
      - if: ${{ inputs.run_linting == true }}
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          cache: "pip"
          cache-dependency-path: "pyproject.toml"
      - if: ${{ inputs.run_linting == true }}
        run: pip install "tox==4.2.4"
      - if: ${{ inputs.run_linting == true && github.ref_name == 'main' }}
        run: sed -i 's/\[tool.setuptools_scm\]/\[tool.setuptools_scm\]\nlocal_scheme = "no-local-version"/' pyproject.toml
      - if: ${{ inputs.run_linting == true }}
        env:
          C_INCLUDE_PATH: ${{ env.pythonLocation }}/include/python3.9
        run: tox run -e lint

  test:
    needs: build
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.allow_failure }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest-sh"]
        python-version: ["3.9", "pypy3.9", "pypy3.10", "3.10", "3.11", "3.12"]
        include:
          - allow_failure: false
            tox-version: "4.2.4"
            include-prefix: "python"
          - python-version: "pypy3.9"
            include-prefix: ""
          - python-version: "pypy3.10"
            include-prefix: ""
          - python-version: "3.12"
            allow_failure: true
    steps:
      - if: ${{ inputs.run_tests == true && inputs.deb-packages != '' && ! startsWith(matrix.os, 'windows') }}
        run: sudo apt-get install -qq ${{ inputs.deb-packages }}
      - if: ${{ inputs.run_tests == true }}
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      - if: ${{ inputs.run_tests == true }}
        run: git lfs pull
      - if: ${{ inputs.run_tests == true }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
          cache-dependency-path: "pyproject.toml"
      - if: ${{ inputs.run_tests == true }}
        run: pip install "tox==${{ matrix.tox-version }}"
      - if: ${{ inputs.run_tests == true && github.ref_name == 'main'  && ! startsWith(matrix.os, 'windows') }}
        run: sed -i 's/\[tool.setuptools_scm\]/\[tool.setuptools_scm\]\nlocal_scheme = "no-local-version"/' pyproject.toml
      - if: ${{ inputs.run_tests == true }}
        env:
          PIP_INDEX_URL: ${{ secrets.DISSECT_PIP_INDEX_URL }}
          C_INCLUDE_PATH: ${{ env.pythonLocation }}/include/${{ matrix.include-prefix }}${{ matrix.python-version }}
        run: tox run -e ${{ matrix.python-version }}
      - if: ${{ inputs.run_tests == true }}
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.DISSECT_CODECOV_TOKEN }}
          env_vars: PYTHON
          files: coverage.xml
          flags: unittests
          verbose: true
      - if: ${{ inputs.run_tests == true }}
        uses: actions/upload-artifact@v3
        with:
          name: coverage
          path: coverage.xml

  publish:
    needs: [lint, test]
    if: ${{ github.ref_name == 'main' || github.ref_type == 'tag' }}
    runs-on: ubuntu-latest-sh
    environment: dissect_publish
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: packages
          path: dist/
      - name: Publish package to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: ${{ secrets.DISSECT_PRIVATE_PYPI_USERNAME }}
          password: ${{ secrets.DISSECT_PRIVATE_PYPI_PASSWORD }}
          repository-url: ${{ secrets.DISSECT_PRIVATE_PYPI_REPOSITORY }}
