name: Dissect docs CI Template
on:
  workflow_call:

jobs:
  docs-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: 'true'

      - uses: fox-it/dissect-workflow-templates/.github/actions/tox-run@cleanup
        with:
          tox-environment: "docs-build"
          cache-dependency-path: "requirements.txt"

