name: Dissect docs CI Template
on:
  workflow_call:

jobs:
  docs-build:
    runs-on: ubuntu-latest
    steps:
      - uses: fox-it/dissect-workflow-templates/.github/actions/git-action@add-step-to-check-docs

      - uses: fox-it/dissect-workflow-templates/.github/actions/docs-build@add-step-to-check-docs
        with:
          cache-dependency-path: "requirements.txt"

